BACKPORT: seccomp: add filter_count field for KernelSU
KernelSU requires struct seccomp to have atomic_t filter_count ,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:
error: no member named 'filter_count' in 'struct seccomp'

Reference: https://github.com/tiann/KernelSU/pull/2708
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Signed-off-by: bagaskara815 <bagaskara815@gmail.com>